######### Copy Highlighted Hexadecimal to Clipboard #########
import os
doc = Document.getCurrentDocument()
seg = doc.getCurrentSegment()
adr = doc.getCurrentAddress()
instr = seg.getInstructionAtAddress(adr)
instlen = instr.getInstructionLength()
len = 30
tempcount = 0
tempcount2 = 0;
homeDir = os.path.expanduser("~")
head, appName = os.path.split(doc.getExecutableFilePath())
path = homeDir + '/hopperDumps/'
if not os.path.exists(path):
    os.makedirs(path)

yararule = open(path+appName+"AutoGen.yara", "w")
yararule.write("rule AutoGenerated\n\t{\n")
yararule.write("\t\tmeta:\n\t\t\tdescription = \"Auto generated\"\n\t\t\tauthor = \"me\"\n\t\t\treference = \"Research\"\n\t\tstrings:\n\t\t\t$hex_string = { ")

hex = ""
for j in range(0, len):
    if (j-tempcount == instlen):
        instr = seg.getInstructionAtAddress(adr+j)
        instlen = instr.getInstructionLength()
        tempcount = j
        tempcount2 = 0
    print("instruction is %s"%(instr.getInstructionString()))
    if (instr.getInstructionString().startswith("xor")):
        if (tempcount2 <= 1):     
            hex += str("%02X " % seg.readByte(adr + j))
            tempcount2+=1
        else:
            hex += "?? "
    elif (instr.getInstructionString().startswith("jmp")):
        hex += "?? "
    else:
        hex += str("%02X " % seg.readByte(adr + j))
    print("Hex is %s"%(hex))
yararule.write("%s }\n"%(str(hex)))
yararule.write("\n\t\tcondition:\n\t\t\t$hex_string\n\t}\n")
yararule.close()
print("Generated rule at %s!"%(path+appName+"Output.yara"))
